### ISSUE TITLE
Tab ranks do not update until player rejoins

### ISSUE THREAD

**Issue by aglaeaaaa** [dimawallhacks-servers/issues#3]
Whenever assigning a rank while in game, it updates everywhere except in tab.

Chat:
![Screenshot 2024-12-17 at 20 34 08](https://github.com/user-attachments/assets/fcf29113-238c-42b6-9992-443124fad2e7)
Tab:
![Screenshot 2024-12-17 at 20 34 32](https://github.com/user-attachments/assets/5c1dff09-88c7-4a6a-8629-a433a98b21c2)

We can probably fix this by reloading tab every once in a while I guess

**Comment by statraum** [comment]
why not reload it when you assign a rank?

**Comment by aglaeaaaa** [comment]
yeah I mean that was my original idea but how would you implement that, as in what's the best way in your opinion

**Comment by statraum** [comment]
Dont know how java or whatever plugins are written in is structured but something along the lines of:

```
void UpdatePlayerRank(p_player Player, int RankId){
   Player.rank == Rankid;
   Scoreboard.refresh();
}
```

**Comment by boonsboos** [comment]
i do think luckperms exposes this in their APi

**Comment by aglaeaaaa** [comment]
> i do think luckperms exposes this in their APi

Haha I was just going over this in discord with blacknwhite, I found https://luckperms.net/wiki/Developer-API-Usage#events

**Comment by pogrammerx** [comment]
In theory Luckperms does Update this itself, atleast it has for the longest period of time, did you try updating Luckperms, or using it standalone on a Test server with same Config? Maybe another plugin is interfering

**Comment by pjesek** [comment]
I recommend using TAB plugin for the tablist and prefixes
 https://modrinth.com/plugin/tab-was-taken

**Comment by mettemfurfur000** [comment]
\i sur hope u guys will use de TAB plugin

**Comment by aglaeaaaa** [comment]
Issue has been fixed, by the looks it things someone installed a new tab plugin.
I will say though I really prefer the way the chat formatting and the rank prefix formatting looked before

**Comment by mettemfurfur000** [comment]
workn on it
